on:
  push:
    branches:
    - master
  pull_request:

jobs:
  license_check:
    runs-on: ubuntu-latest
    name: Validate Licenses
    steps:
    - name: Checkout the code
      uses: actions/checkout@master
    - name: Perform checks
      uses: jamie/license_finder_action@master
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: license_finder.log
        path: output/license_finder.log
        if-no-files-found: ignore
