on:
  push:
    branches:
    - master
  pull_request:

jobs:
  license_check:
    runs-on: ubuntu-latest
    name: Check for unapproved licenses
    steps:
    - name: Checkout the code
      uses: actions/checkout@master
    - name: Perform checks
      id: license-check
      with:
        package_manager: 'bundler'
      uses: jamie/license_finder_action@master

